# Generated by Django 5.2.4 on 2025-11-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_alter_user_phone'),
        ('user', '0003_fix_phone_field'),
    ]

    operations = [
    ]
