# Generated by Django 5.2.7 on 2025-11-25 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_fix_phone_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('visitor_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('session_fingerprint', models.CharField(blank=True, db_index=True, max_length=128)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('client_language', models.CharField(blank=True, max_length=32)),
                ('client_timezone', models.CharField(blank=True, max_length=64)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile'), ('bot', 'Bot / Crawler'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('device_family', models.CharField(blank=True, max_length=120)),
                ('os', models.CharField(blank=True, max_length=120)),
                ('browser', models.CharField(blank=True, max_length=120)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('isp', models.CharField(blank=True, max_length=255)),
                ('referrer', models.TextField(blank=True)),
                ('entry_url', models.TextField(blank=True)),
                ('exit_url', models.TextField(blank=True)),
                ('landing_page_title', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('utm_term', models.CharField(blank=True, max_length=120)),
                ('is_bot', models.BooleanField(default=False)),
                ('bot_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page view'), ('api_request', 'API Request'), ('interaction', 'UI Interaction'), ('auth', 'Authentication'), ('custom_event', 'Custom Event')], default='page_view', max_length=50)),
                ('url', models.TextField()),
                ('path', models.TextField()),
                ('view_name', models.CharField(blank=True, max_length=255)),
                ('handler', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('referrer', models.TextField(blank=True)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='user.usersession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['visitor_id', 'started_at'], name='user_userse_visitor_1df668_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_authenticated'], name='user_userse_is_auth_f54dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['event_type'], name='user_userac_event_t_4e501a_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['timestamp'], name='user_userac_timesta_deb832_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['response_time_ms'], name='user_userac_respons_22adee_idx'),
        ),
    ]
