# Generated by Django 5.2.4 on 2025-11-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_20251120_2027'),
        ('user', '0004_usersession_useractivity_and_more'),
    ]

    operations = [
    ]
